### ISSUE TITLE
fix issue with deploy-pre-release

### ISSUE THREAD

**Issue by craig8** [eclipse-volttron/volttron-core#63]
https://github.com/eclipse-volttron/volttron-core/blob/develop/.github/workflows/deploy-pre-release.yml

The increase in latest number is not being increased properly.

```
Run ncipollo/release-action@v1
  with:
    artifacts: dist/*.gz,dist/*.whl
    artifactErrorsFailBuild: true
    generateReleaseNotes: true
    commit: refs/heads/develop
    prerelease: true
    tag: v10.0.1a15
    token: ***
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
  env:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    PYTHON_VERSION: 3.8
    PROJECT_NAME: test-release-actions
    RUNS_ON: ubuntu-[2](https://github.com/eclipse-volttron/volttron-core/runs/7697174508?check_suite_focus=true#step:13:2)0.04
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/eclipse-volttron/volttron-core/runs/7697174508?check_suite_focus=true#step:13:3).8.13/x6[4](https://github.com/eclipse-volttron/volttron-core/runs/7697174508?check_suite_focus=true#step:13:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.13/x64/lib
    VENV: .venv/bin/activate
    NEW_TAG: v10.0.1a1[5](https://github.com/eclipse-volttron/volttron-core/runs/7697174508?check_suite_focus=true#step:13:5)
Error: Error 4[22](https://github.com/eclipse-volttron/volttron-core/runs/7697174508?check_suite_focus=true#step:13:22): Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

**Comment by bonicim** [comment]
It appears that the increase in latest number is working as expected. The issue is that the repo is missing tag `v10.0.1.-alpha.15`; it appears that that tag was mislabeled as `v10.0.1a15`. 
 
One of the commands in the Bump Version step in 'deploy-pre-release.yml' workflow attempts to get all the version tags of the repo in reverse order. The command, `git tag -l "v*" | sort --reverse -V`, produces the following output:

```
v10.0.1-alpha.14
v10.0.1-alpha.13
v10.0.1-alpha.12
v10.0.1-alpha.11
v10.0.1-alpha.10
v10.0.1-alpha.9
v10.0.1-alpha.8
v10.0.1-alpha.7
v10.0.1-alpha.6
v10.0.1-alpha.5
v10.0.1-alpha.4
v10.0.1-alpha.3
v10.0.1-alpha.2
v10.0.1-alpha.1
v10.0.1-alpha.0
v10.0.1a15
v10.0.1a3
```

Note that the first line has `v10.0.1-alpha.14`, however, we also have a tag labeled `v10.0.1a15`. If `v10.0.1a15` was correctly labeled `v10.0.1-alpha.15`, then the [command in Bump Version step](https://github.com/eclipse-volttron/volttron-core/issues/63) would produce the right tag, thus ensuring that the [release action step](https://github.com/eclipse-volttron/volttron-core/blob/develop/.github/workflows/deploy-pre-release.yml#L113) would succeed. 

The [key steps in Bump Version]() are recreated below:
 
```
$ git tag -l "v*" | sort --reverse -V | sed -n 1p
v10.0.1-alpha.15

$ poetry version v10.0.1-alpha.15
Bumping version from 0.3.0 to v10.0.1-alpha.15

$ poetry version prerelease
Bumping version from v10.0.1-alpha.15 to 10.0.1a16

$ poetry version --short
10.0.1a16
``` 

If we push a tag labeled v10.0.1-alpha.15 and reran the deploy-release action, the Workflow should at least get past this error.

**Comment by craig8** [comment]
So what's interesting is the difference in the poetry version --short.  Why would one give alpha and one a.  I think I remember seeing this difference on another project.

**Comment by bonicim** [comment]
> So what's interesting is the difference in the poetry version --short. Why would one give alpha and one a. I think I remember seeing this difference on another project.

The command `poetry version prerelease` is giving some different behavior depending on the version of poetry. Note how that command is using 'a' instead of 'alpha':


```
poetry --version
>> Poetry version 1.2.0b2

poetry version v10.0.1-alpha.14
>> Bumping version from 0.3.0 to v10.0.1-alpha.14

poetry version prerelease
>> Bumping version from v10.0.1-alpha.14 to 10.0.1a15
```


```
poetry --version
>> Poetry version 1.1.14

poetry version v10.0.1-alpha.14
>> Bumping version from 0.3.0 to v10.0.1-alpha.14

poetry version prerelease
>> Bumping version from v10.0.1-alpha.14 to 10.0.1-alpha.15
```


I quickly scanned poetry's [release notes](https://github.com/python-poetry/poetry/releases) for any changes related to `poetry version` for  versions 1.1.14 and 1.2.0.b2. Didn't find anything helpful.  

This current workflow uses [1.2.0.b2](https://github.com/eclipse-volttron/volttron-core/blob/develop/.github/workflows/deploy-pre-release.yml#L50). Changing the version to 1.1.14 would resolve this issue.

**Comment by bonicim** [comment]
One concern about using version 1.1.14 is that it doesn't support [dependency groups](https://python-poetry.org/blog/announcing-poetry-1.2.0a2/#dependency-groups) which is a new feature in 1.2.0.b2. I know some of the volttron modular repos use dependency groups in their pyproject.toml. Any Github Workflow should use the poetry version that defined in 'pyproject.toml' to ensure that installation works as expected.

**Comment by craig8** [comment]
So the only way to get that is to parse the yml file not a big deal, but it also has to be set correctly within the project...the core is set with 
requires = ["poetry-core>=1.0.0"]

Which obviously isn't true because it has the dependency thingy.  This also means our poetry copier should need to be updated to support whatever version we are wanting to support.

**Comment by craig8** [comment]
I think using the 1.2b and using:

```
git tag -l "v*" | grep --invert-match '-' | sort --reverse -V  | sed -n 1p
```
will do what we want.
